# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Indgredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='indgredients',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menus.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='dishtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menus.RestaurantDishType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menus.Kitchen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='sopin_dishtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menus.DishType'),
            preserve_default=False,
        ),
    ]
