# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20160220_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='indgredient',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
